### ISSUE TITLE
mipsel_24kc.ipk安装问题

### ISSUE THREAD

**Issue by Passwww** [yiguihai/luci-app-k3screenctrl#1]
R6220刷了openwrt，安装luci-app-passw-plus_1.2-2_mipsel_24kc.ipk

提示
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-passwall-plus:
 * 	bash
 * 	curl
 * opkg_install_cmd: Cannot install package luci-app-passwall-plus.

_不知如何解决？？_

**Comment by yiguihai** [comment]
> R6220刷了openwrt，安装luci-app-passw-plus_1.2-2_mipsel_24kc.ipk
> 
> 提示
> Collected errors:
> 
> * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-passwall-plus:
> * bash
> * curl
> * opkg_install_cmd: Cannot install package luci-app-passwall-plus.
> 
> _不知如何解决？？_

需要安装 bash 和 curl
